name: Release

on:
  push:
    branches:
    - main
    tags:
    - v*.*.*

jobs:
  release:
    if: github.repository_owner == 'Platzii'
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Create ZIP
      shell: bash
      run: |
        cd "${{ github.workspace }}/custom_components/evcnet"
        zip homeassistant-evcnet.zip -r ./
    - name: Release
      uses: softprops/action-gh-release@v2.4.1
      with:
        files: ${{ github.workspace }}/custom_components/evcnet/homeassistant-evcnet.zip
